name: Java CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven (with skipped tests)
        run: mvn clean install -Duser.language=en -Duser.country=US -DskipTests
      - name: Run tests
        run: mvn test -Duser.language=en -Duser.country=US -Denv=github-actions
