name: Java CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install latest ChromeDriver
        run: |
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          echo "Using ChromeDriver version: $DRIVER_VERSION"
          curl -s -L -o /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
          unzip /tmp/chromedriver.zip -d /tmp
          sudo mv /tmp/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run tests
        run: xvfb-run -a mvn test -Denv=github-actions
        env:
          DISPLAY: :99.0

      # Uploading test reports
      - name: Generate Surefire Report
        if: always()
        run: mvn surefire-report:report-only

      - name: Deploy to GitHub Pages
        if: always()
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --branch gh-pages https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} gh-pages
          rsync -av --exclude='.git' target/ gh-pages/
          cd gh-pages
          echo "<meta http-equiv='refresh' content='0; url=extent-report.html'>" > index.html
          git add .
          git commit -m "Deploy report - $GITHUB_SHA"
          git push origin gh-pages

      - name: Upload ExtentReports
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: extent-report
          path: extent-report.html

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: target/screenshots
